language: cpp
os: osx
osx_image: xcode7.2
compiler: clang
install: true
script: make

# Reinstall CocoaPods because the preinstalled CocoaPods crashes with a segmentation fault.
before_install:
  - rvm install ruby-1.9.3
  - rvm --default use 1.9.3
  - gem install cocoapods
