language: cpp
os: osx
osx_image: xcode7.2
compiler: clang
install: true
script: make

# Reinstall CocoaPods because the preinstalled CocoaPods crashes with a segmentation fault.
before_install:
  - gem install cocoapods
